### ISSUE TITLE
dmdserver fails to connect over USB to ZeDMD on 5.1.2 firmware

### ISSUE THREAD

**Issue by DaveBullet1050** [PPUC/libzedmd#32]
Hi there

The latest dmdserver fails to connect when using the latest 5.1.2 firmware.  Here's the error:
```
# /usr/bin/dmdserver -l -v -c /userdata/system/configs/dmdserver/config.ini

Loaded config file
Opening DMDServer, listening for TCP connections on localhost:6789
Searching for ZeDMD...
ZeDMD candidate: device=/dev/ttyUSB0
Unable to find ZeDMD
No DMD displays found.
```  

When I re-flash 5.1.1 I get:
```
# /usr/bin/dmdserver -l -v -c /userdata/system/configs/dmdserver/config.ini
Loaded config file
Opening DMDServer, listening for TCP connections on localhost:6789
Searching for ZeDMD...
ZeDMD candidate: device=/dev/ttyUSB0
ZeDMD 5.1.1 found: device=/dev/ttyUSB0, width=128, height=32
ZeDMDComm run thread starting
```  
In both cases - the only change is the firmware.  To get the error, I am using the following:
1. Recompiled master (https://github.com/vpinball/libdmdutil) for dmdserver - I used the vpinball version as the PPUC fork was behind a few commits when I compiled on Feb 2nd
2. Latest 5.1.2 firmware for a 128x32 SD panel (https://github.com/PPUC/ZeDMD/releases/download/v5.1.2/ZeDMD-128x32.zip)
3. Latest libzedmd.so.0.9.1 (https://github.com/PPUC/libzedmd/releases/tag/v0.9.1)

I've recompiled all from source code on a Raspberry Pi 3b+ with this aarch64 kernel
```
Linux alarm 6.13.0-2-aarch64-ARCH #1 SMP PREEMPT_DYNAMIC Wed Jan 22 07:01:59 MST 2025 aarch64 GNU/Linux
```  

Here's my /userdata/system/configs/dmdserver/config.ini I am using when launching dmdserver:
```
[DMDServer]
AltColor = 1

[ZeDMD]
SaveSettings = 0
Brightness = 15
RGBOrder = 0

[ZeDMD-WiFi]
Enabled = 0
WiFiAddr = 192.168.1.19

[Pixelcade]
Enabled = 0
```  

My runtime host is Batocera V41

No other client / process is using /dev/ttyUSB0 (ZeDMD), so it isn't a failure to open the port due to being exclusively used by another process.

Thanks,
David.

**Comment by mkalkbrenner** [comment]
I just merged the latest code in libdmdutil:
https://github.com/vpinball/libdmdutil/pull/57

Can you test with that version of dmdserver?

**Comment by DaveBullet1050** [comment]
Thanks for your speedy response - but I still get the same dmdserver error.  Here's what I did:
1. Reflashed 5.1.2 firmware 
2. Went to repo vpinball/libdmdutil and downloaded all code from master branch - i.e. https://github.com/vpinball/libdmdutil/archive/refs/heads/master.zip
3. Compiled / built
4. Deployed all libraries and checked they were properly symlinked and execuable and new dmdserver, eg:

[root@BATOCERA_V41 /usr/lib]# ls -l libze*
lrwxrwxrwx 1 root root     17 Feb  7 09:57 libzedmd.so -> libzedmd.so.0.9.1
-rwxr-xr-x 1 root root 125712 Dec 17 10:44 libzedmd.so.0.7.4
-rwxr-xr-x 1 root root 228240 Feb  1 19:33 libzedmd.so.0.9.0
-rwxr-xr-x 1 root root 229208 Feb  7 08:28 libzedmd.so.0.9.1

and
lrwxrwxrwx 1 root root       19 Jan  1  1970 libdmdutil.so -> libdmdutil.so.0.8.0
-rwxr-xr-x 1 root root   105552 Dec 17 10:44 libdmdutil.so.0.7.0
-rwxr-xr-x 1 root root   163032 Feb  7 08:32 libdmdutil.so.0.8.0

also copied over all other built libraries - libpupdmd.so.0.4.1, libserialport.so.0.1.1, libserum.so.2.0.2, libsockpp.so.1.0.0 and these also correctly symlinked

PPS: I do like how you have changed the firmware in 5.1.2 to default after a while to a clear screen and not ZeDMD image.  Also I am a personal user and not using this for any commercial reasons. I thought I should make that clear.  I love your work and this has been a fun project. Thanks for building / maintaining it for our community.

**Comment by mkalkbrenner** [comment]
libzedmd contains `zedmd-test`. Run this one first to check if ZeDMD could be connected.

In your posting above, I don't see that you installed a new dmdserver version. That is required because libzedmd's API changed. Just adding the libs is not enough.

For different reasons I had to break backward compatibility of libzedmd and ZeDMD. Mainly to support the USB CDC mode of the S3.
The new handshake implementation should ensure backward compatibility for a longer time.

BTW there's already a PR for batocera to use all the new stuff and it is suppoded to be merged into batocera 42 beta soon.

**Comment by DavidT1050** [comment]
Thanks - I'll run zedmd-test tonight and report back.

I did try a new dmdserver compile, however when I downloaded master (maybe a mistake) from either repo (PPUC fork or vpinball) which seem to be at the same commit level anyway, the dmdserver build is still referring to the libzedmd v.0.9.1 SHA (archive). I don't know if there is a new one available for 0.9.2 which I think you are recommending I compile with.

If you can point me to how I rebuild dmdserver with libzedmd 0.9.2 binding, then I'd appreciate it please (or wait until you release it officially).

Thanks for the batocera v42 heads up.  I am preferring to get this working on v41 purely as I don't want to break anything else (I have a really stable platform now with everything working).

I might use the discord to ask about GIF/PNG upload performance to the ZeDMD as it seems slow over USB to on my Pi3B+ (relative term I know)

**Comment by DaveBullet1050** [comment]
First zedmd-test build library dependencies, just to make sure I'm on latest:
```
ldd ./zedmd-test
        linux-vdso.so.1 (0x0000007f8da80000)
        libzedmd.so.0.9.2 => /usr/lib64/libzedmd.so.0.9.2 (0x0000007f8da00000)
        libserialport.so.0 => /usr/lib64/libserialport.so.0 (0x0000007f8d9d0000)
        libsockpp.so.1 => /usr/lib64/libsockpp.so.1 (0x0000007f8d9a0000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x0000007f8d75b000)
        libm.so.6 => /lib64/libm.so.6 (0x0000007f8d6d6000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000007f8d6bc000)
        libc.so.6 => /lib64/libc.so.6 (0x0000007f8d525000)
        /lib/ld-linux-aarch64.so.1 (0x0000007f8da81000)
```  

ZeDMD v5.1.3 ESP32 firmware

zedmd-test ran fine.  It swept through the colours from bottom to top then played 
`Render raw: test/rgb888_128x32/0022.raw`  

frames (car driving down a road bordered by forest).  Did that for ~ 1 - 2 mins

So, I suspect once I have dmdserver compiled to use libzedmd.0.9.2, all will be good.
